[package]
name = "rust_python_example"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_python_example"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module"] }

[profile.release]
lto = true